### ISSUE TITLE
undefined reference to `Jp_LeftToeJoint_src' 

### ISSUE THREAD

**Issue by raysworld** [UMich-BipedLab/cassie_alip_mpc_controller#1]
Hi, 
I am trying to run this controller on Matlab 2020b and encountered the following issues:
```log
"C:\Program Files\Matlab\R2020b\bin\win64\mex.exe" -R2018a -silent LDFLAGS="$LDFLAGS  " -output Mpc_SimMechanics_with_standing_cgxe.mexw64 @Mpc_SimMechanics_with_standing_cgxe.mol       
m_hyQXJW0uAGcKZhYj4mpzyD.obj:m_hyQXJW0uAGcKZhYj4mpzyD.c:(.text+0x3521): undefined reference to `Jp_LeftToeJoint_src' 
m_hyQXJW0uAGcKZhYj4mpzyD.obj:m_hyQXJW0uAGcKZhYj4mpzyD.c:(.text+0x3579): undefined reference to `Jp_RightToeJoint_src' 
m_hyQXJW0uAGcKZhYj4mpzyD.obj:m_hyQXJW0uAGcKZhYj4mpzyD.c:(.text+0x6790): undefined reference to `p_LeftToeJoint_src' 
m_hyQXJW0uAGcKZhYj4mpzyD.obj:m_hyQXJW0uAGcKZhYj4mpzyD.c:(.text+0x6833): undefined reference to `p_RightToeJoint_src' 
collect2.exe: error: ld returned 1 exit status 
 
gmake: *** [Mpc_SimMechanics_with_standing_cgxe.mexw64] Error -1 
```
Has anyone met the same issue and already found a solution to solve this? Many thanks!

**Comment by grantgib** [comment]
I haven't tried running the code on later versions of Matlab, as some Visual Studio 2015 compilers can cause conflicts. Can you try with 2017b. 

Alternatively, run the 'start_up_sim.m' script to source the paths. This could be why some of the source code is not found.

**Comment by raysworld** [comment]
> I haven't tried running the code on later versions of Matlab, as some Visual Studio 2015 compilers can cause conflicts. Can you try with 2017b.
> 
> Alternatively, run the 'start_up_sim.m' script to source the paths. This could be why some of the source code is not found.

Hi, @grantgib ,
Thanks for your reply. Matlab 2017b seems to work fine with the code.

Best regards,
